scrape_configs:
  - job_name: 'nodejs-app'
    static_configs:
      - targets: ['localhost:3001']
        labels:
          instance: 'app-instance-1'
      - targets: ['localhost:3002']
        labels:
          instance: 'app-instance-2'


# scrape_configs:
#   - job_name: 'nodejs-app-1'
#     scrape_interval: 15s
#     static_configs:
#       - targets: ['localhost:3001']

#   - job_name: 'nodejs-app-2'
#     scrape_interval: 15s
#     static_configs:
#       - targets: ['localhost:3002']

# scrape_configs:
#   - job_name: 'nodejs-app'
#     scrape_interval: 15s
#     static_configs:
#       - targets: ['localhost:3001']
#         labels:
#           instance: 'app-instance-1'
#       - targets: ['localhost:3002']
#         labels:
#           instance: 'app-instance-2'
